language: node_js
node_js:
- '8'
notifications:
  email: markusgilg@outlook.de
jobs:
  include:
  - stage: test
    script: npm run coverage
deploy:
  provider: npm
  email: markusgilg@outlook.de
  api_key:
    secure: pn/vehNz+MOjTsJ5sIK15KtFdZanew7Uzi89a7wBOaa4EMv2ksIfRwuEh5//LgQcBc6iGYbzxoWmAGkQr+jOknqmBdcdDkvOvlKEfQB2MBhCFxD07J1dbj+DAhSay/JY8gbSDd9X1NJufGjFokpdYUlAUU1adFooaflZWXh2dFx0rJvYDqIJOBNL3Lj0v1UM8q+juGpVnuQWN6B1SaBB0Hsz05vTxFJ5Q0NgewaHGlSQSvdQZMt/UK2Xwqg5QuYIVgDQ4t/4MJjfWnOaxnZ7OK3eeLQHugN3d3KalTooO4RODaX7vh+oQC6G0zuxvCoA+I5UMd9wK8Bik519kP3m98EP6O9gDvi9rPtR8S62u56kQDiG/PJ/gmXdeMkiP5EbMno5Q5bPbW1duAbVqp5CYH3rGGYFs8vsm6dPUBvB9yGszVwl0qHnjjjbHq6bfc3TSThaVEYFyi8m/liqAoYOOYpur+du5EWsWp9YniQqCo1hdznks9+VPcEAEyvxTFlLNIZapV3+6QvAX96c8n6NXxs2GP4S8gFl3aNP1x+Rpww41ZAHMggXjn5+9UQkRvB0fshx2Y5XkHa93E4ykQu8lsQLtzjqcmxmbY8osIhRAEVwe5hQrlrZRzD1FsJOsdSc2oVKyuNCePJfnKp1uw/8Xl98SwM0vT9dHY5+SPhsvEA=
  on:
    repo: nodejayes/acts
    branch: master
